### ISSUE TITLE
Schema View: panics if nested object in query is not declared in SDL

### ISSUE THREAD

**Issue by islamaliev** [sourcenetwork/defradb#2189] opened 2024-01-11 10:35 UTC
```go
func TestView_NotUsedNested(t *testing.T) {
	test := testUtils.TestCase{
		Description: "One to many view with alias on inner object",
		Actions: []any{
			testUtils.SchemaUpdate{
				Schema: `
					type Author {
						name: String
						books: [Book]
					}
					type Book {
						name: String
						author: Author
					}
				`,
			},
			testUtils.CreateView{
				Query: `
					Author {
						name
						books {
							name
						}
					}
				`,
				SDL: `
					type AuthorView {
						name: String
					}
				`,
			},
			// bae-ef9cd756-08e1-5f23-abeb-7b3e6351a68d
			testUtils.CreateDoc{
				CollectionID: 0,
				Doc: `{
					"name":	"Harper Lee"
				}`,
			},
			testUtils.CreateDoc{
				CollectionID: 1,
				Doc: `{
					"name":	"To Kill a Mockingbird",
					"author_id": "bae-ef9cd756-08e1-5f23-abeb-7b3e6351a68d"
				}`,
			},
			testUtils.Request{
				Request: `
					query {
						AuthorView {
							name
						}
					}
				`,
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```
Stacktrace:
```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 11 [running]:
testing.tRunner.func1.2({0x104430cc0, 0x140001a2798})
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1529 +0x384
panic({0x104430cc0, 0x140001a2798})
	/Users/islam/sdk/go1.20.7/src/runtime/panic.go:884 +0x204
github.com/sourcenetwork/defradb/core.(*DocumentMapping).SetFirstOfName(...)
	/Users/islam/dev/sourcenetwork/defradb/core/doc.go:180
github.com/sourcenetwork/defradb/planner.(*viewNode).Value(0x14000620000)
	/Users/islam/dev/sourcenetwork/defradb/planner/view.go:72 +0x23c
github.com/sourcenetwork/defradb/planner.(*selectNode).Next(0x140005b84e0)
	/Users/islam/dev/sourcenetwork/defradb/planner/select.go:157 +0x60
github.com/sourcenetwork/defradb/planner.(*selectTopNode).Next(0x140000e6d18?)
	/Users/islam/dev/sourcenetwork/defradb/planner/select.go:70 +0x28
github.com/sourcenetwork/defradb/planner.(*Planner).executeRequest(0x18?, {0x1041bdd40?, 0x1400080fea0?}, {0x10453dca0, 0x1400046d720})
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:520 +0x48
github.com/sourcenetwork/defradb/planner.(*Planner).RunRequest(0x1400000e120?, {0x104531170, 0x1400019e018}, 0x1400080fea0)
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:575 +0x230
github.com/sourcenetwork/defradb/db.(*db).execRequest(0x14000108d10, {0x104531170?, 0x1400019e018}, {0x103c820e2, 0x40}, {0x1045415a8?, 0x14000a3f500})
	/Users/islam/dev/sourcenetwork/defradb/db/request.go:53 +0x3c8
github.com/sourcenetwork/defradb/db.(*implicitTxnDB).ExecRequest(0x140000100d0, {0x104531170, 0x1400019e018}, {0x103c820e2, 0x40})
	/Users/islam/dev/sourcenetwork/defradb/db/txn_db.go:45 +0x150
github.com/sourcenetwork/defradb/tests/integration.executeRequest(0x140001fa8c0, {{0x0, 0x0}, {0x0, 0x0}, {0x103c820e2, 0x40}, {0x0, 0x0, 0x0}, ...})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:1528 +0x11c
github.com/sourcenetwork/defradb/tests/integration.performAction(0x140001fa8c0?, 0x0?, {0x104441dc0?, 0x14000b95880?})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:306 +0x5bc
github.com/sourcenetwork/defradb/tests/integration.executeTestCase({0x104531170?, 0x1400019e018}, 0x140000a3380, {0x140009463a0, 0x2, 0x2}, {{0x103c65514, 0x2b}, {0x1400003cc80, 0x5, ...}, ...}, ...)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:205 +0x80c
github.com/sourcenetwork/defradb/tests/integration.ExecuteTestCase(0x104441dc0?, {{0x103c65514, 0x2b}, {0x1400003cc80, 0x5, 0x5}, {0x0, {0x0, 0x0, 0x0}}})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:161 +0x580
github.com/sourcenetwork/defradb/tests/integration/view/one_to_many.TestView_NotUsedNested(0x0?)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/view/one_to_many/with_alias_test.go:228 +0x2dc
testing.tRunner(0x140000a3380, 0x1045152c8)
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1576 +0x10c
created by testing.(*T).Run
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1629 +0x368
FAIL	github.com/sourcenetwork/defradb/tests/integration/view/one_to_many	0.878s
FAIL
```

**Comment by AndrewSisley** [comment] 2024-01-11 14:12
This is likely a duplicate of https://github.com/sourcenetwork/defradb/issues/2183

**Closed** 2024-01-11 15:44 UTC
Labels: bug, area/query, area/schema
